language: python

python:
  - '2.7'
  - '3.5'

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python -m unittest discover; fi

deploy:
  provider: pypi
  user: wenzhel
  password:
    secure: W7ZV9pxxeBKfU7Yfa568N0xbkGZilRe53YiiC1CyxR0BbI+6EWN2R96xUr/IF7Pk4bpY7+wK1Al73TZ2YGhtDUQTMgIVAbpBW8D7R7tl9UgdUhSOMwGTJo440Mw6K8/CGZbEHhKhP3YKOra6OkHnQpyXg80+XgEhEXHqHAk93IZPKLxZz7tf0pFpYnCLK6w+s1EPLgzmn3SN2bz9xasI1dLnq3XYGlhEzb1DWm0FYoKcPIdoOnOyt+ZPMa7EHRHED1Bg5RT1wtKffnR4sCWQShatqzXZI+htxHQj/YW4d3u+2hgzkd/K4Ekt1/hEJr2lVtTooMgYm5bQT8xBCj1hcbxd+tMnnzs+bCVgdcRLoH61Cb8qd/jpkT1JWPUZ18z4sO3DGCBcMUizZxQMiIzKL6jhWE4B88MkS5GvRQYrSUzPOwMWkWZ7XdZP99TNHmwnGz6wQNeDOhHqVKFEasgdaxgc00SCrz8ZTulXK/Ia24O/jwQH+WwktELohk2HSB00ofeQlh1s3KMzyPDf8HaZF/wMS5QoEEsLo6nACjj70BNIRbAWL/kwUeA9Mq7urUTyGYK8Nn1UFHD7BrN6NTRl3nwLR8x7OgDHybIvcLsTUX8KEWRbZUCdpMyc0YUXPMeAORnvoNJXKgH6+dwYfnW/7DulYJqBFYRKNjRmttsxhlY=
  on:
    tags: true